name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ "windows-latest", "macos-latest" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Build (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: flutter build windows
      
      - name: Create ZIP file (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: 7z a -tzip wormhole ./build/windows/runner/Release/*
      
      - name: Upload artifact (Windows)
        if: ${{ runner.os == 'Windows' }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: wormhole-windows
          path: wormhole.zip
      
      - name: Build (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: flutter build macos
      
      - name: Create ZIP file (MacOS)
        if: ${{ runner.os == 'macOS' }}
        run: 7z a -tzip wormhole ./build/macos/Build/Products/Release/*
      
      - name: Upload artifact (MacOS)
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: wormhole-macos
          path: wormhole.zip
          
