name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      
      - name: Build
        run: flutter build windows
      
      - name: Create ZIP file
        run: 7z a wormhole-windows.zip ./build/windows/runner/Release/*
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: wormhole-windows
          path: wormhole-windows.zip
          
